#!/usr/bin/env bash
# Operational command helpers for linux-maint.

reason_next_steps(){
  local tok="$1"
  case "$tok" in
    missing_dependency)
      echo "Next steps:"
      echo "- Install the required command on the runner/host."
      echo "- See: linux-maint deps"
      ;;
    missing_optional_cmd)
      echo "Next steps:"
      echo "- Install the optional tool if you need this monitor."
      echo "- Otherwise treat this as expected SKIP."
      ;;
    ssh_unreachable)
      echo "Next steps:"
      echo "- Verify DNS/keys/firewall and LM_SSH_OPTS."
      echo "- Try: ssh <host> from the runner."
      ;;
    service_failed|failed_units)
      echo "Next steps:"
      echo "- Check: systemctl status <unit> and recent journal logs."
      echo "- Restart or fix the failing unit."
      ;;
    service_inactive)
      echo "Next steps:"
      echo "- Enable/start the unit if it is expected to be active."
      ;;
    timeout|runtime_exceeded)
      echo "Next steps:"
      echo "- Increase MONITOR_TIMEOUT_SECS or per-monitor timeouts."
      echo "- Re-run linux-maint run or the specific monitor."
      ;;
    config_missing)
      echo "Next steps:"
      if [[ "$MODE" == "repo" ]]; then
        echo "- Run: linux-maint init"
      else
        echo "- Run: sudo linux-maint init"
      fi
      echo "- Populate the missing config file and re-run."
      ;;
    baseline_missing)
      echo "Next steps:"
      echo "- Generate baseline: linux-maint baseline <ports|configs|users|sudoers> --update"
      ;;
    security_updates_pending|updates_pending)
      echo "Next steps:"
      echo "- Apply your distro update workflow, then re-check."
      ;;
    timer_missing|timer_disabled|timer_inactive)
      echo "Next steps:"
      echo "- Install/enable linux-maint.timer (installed mode)."
      ;;
    permission_denied)
      echo "Next steps:"
      echo "- Re-run with sudo/root if the operation is meant to mutate installed paths."
      echo "- Verify file ownership and writable directories."
      ;;
    *)
      echo "Next steps:"
      echo "- Re-run linux-maint status --reasons 10"
      echo "- See docs/REASONS.md and docs/troubleshooting.md for guidance."
      ;;
  esac
}

resolve_reasons_doc_path() {
  local f="$REPO_ROOT/docs/REASONS.md"
  if [[ ! -f "$f" ]]; then
    local alt
    for alt in \
      "$SHARE/docs/REASONS.md" \
      "$PREFIX/share/Linux_Maint_ToolKit/docs/REASONS.md" \
      "$PREFIX/share/linux-maint/docs/REASONS.md" \
      "/usr/share/Linux_Maint_ToolKit/docs/REASONS.md" \
      "/usr/share/linux-maint/docs/REASONS.md" \
      "/usr/share/linux_maint/docs/REASONS.md"
    do
      if [[ -f "$alt" ]]; then
        f="$alt"
        break
      fi
    done
  fi
  printf '%s\n' "$f"
}

linux_maint_cmd_tune() {
  local sub="${1:-}" CFG_DIR TUNE_LAST_RUN_LOG_DIR CONF SRC_DIR ALT tmpl
  shift || true
  case "$sub" in
    dark-site)
      CFG_DIR="$(linux_maint_effective_cfg_dir)"
      TUNE_LAST_RUN_LOG_DIR="$(linux_maint_effective_log_dir)"
      CONF="$CFG_DIR/linux-maint.conf"

      if [[ "$MODE" == "installed" ]]; then
        need_root_for tune
      fi

      if [[ ! -d "$CFG_DIR" ]]; then
        mkdir -p "$CFG_DIR" 2>/dev/null || { echo "ERROR: cannot create $CFG_DIR (try sudo)" >&2; exit 1; }
      fi
      if [[ ! -w "$CFG_DIR" ]]; then
        echo "ERROR: cannot write to $CFG_DIR (try sudo)" >&2
        exit 1
      fi

      SRC_DIR="$REPO_ROOT/etc/linux_maint"
      if [[ "$MODE" == "installed" ]]; then
        ALT="$SHARE/templates/linux_maint"
        [[ -d "$ALT" ]] && SRC_DIR="$ALT"
      fi
      tmpl="$SRC_DIR/linux-maint.conf.example"
      if [[ ! -f "$CONF" ]]; then
        if [[ -f "$tmpl" ]]; then
          cp -f "$tmpl" "$CONF"
        else
          cat > "$CONF" <<'EOF'
# linux-maint.conf - main configuration (KEY=VALUE)
# Generated by linux-maint tune dark-site
EOF
        fi
        echo "create: $CONF"
      fi

      TUNE_LAST_RUN_LOG_DIR="$TUNE_LAST_RUN_LOG_DIR" python3 - "$CONF" <<'PY'
import os, re, sys, tempfile

conf_path = sys.argv[1]
last_run_log_dir = os.environ.get("TUNE_LAST_RUN_LOG_DIR", "/var/log/health").replace('"', '\\"')
settings = [
    ("LM_DARK_SITE", "true"),
    ("LM_LOCAL_ONLY", "true"),
    ("LM_NOTIFY_ONLY_ON_CHANGE", "1"),
    ("MONITOR_TIMEOUT_SECS", "300"),
    ("LM_LAST_RUN_MAX_AGE_MIN", "1800"),
    ("LM_LAST_RUN_LOG_DIR", f"\"{last_run_log_dir}\""),
    ("LM_FS_RO_EXCLUDE_RE", "'^(proc|sysfs|devtmpfs|tmpfs|devpts|cgroup2?|cgroup|debugfs|tracefs|mqueue|hugetlbfs|pstore|squashfs|overlay|rpc_pipefs|autofs|fuse\\\\..*|binfmt_misc|iso9660)$'"),
]

with open(conf_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

found = {k: False for k, _ in settings}
replaced = {k: False for k, _ in settings}
actions = []
active_present = {k: False for k, _ in settings}

for line in lines:
    for key, _ in settings:
        if re.match(r"\s*%s\s*=" % re.escape(key), line):
            active_present[key] = True

for i, line in enumerate(lines):
    for key, val in settings:
        if found[key]:
            continue
        if re.match(r"\s*#?\s*%s\s*=" % re.escape(key), line):
            if line.lstrip().startswith("#"):
                if active_present[key]:
                    continue
                lines[i] = f"{key}={val}\n"
                replaced[key] = True
                actions.append(f"set: {key}={val} (was commented)")
            else:
                found[key] = True
                actions.append(f"keep: {key} (already set)")
            break

for key, val in settings:
    if found[key] or replaced[key]:
        continue
    lines.append(f"{key}={val}\n")
    actions.append(f"add: {key}={val}")

fd, tmp_path = tempfile.mkstemp(prefix="linux_maint_conf.", dir=os.path.dirname(conf_path))
with os.fdopen(fd, "w", encoding="utf-8") as f:
    f.writelines(lines)
os.replace(tmp_path, conf_path)

for a in actions:
    print(a)
PY
      ;;
    *)
      echo "Usage: linux-maint tune dark-site" >&2
      exit 2
      ;;
  esac
}

linux_maint_cmd_baseline() {
  local target="${1:-}" script scripts_dir
  shift || true
  local BASELINE_UPDATE=0 BASELINE_LOCAL=0 BASELINE_DIFF=0 BASELINE_SHOW=0 BASELINE_JSON=0
  local BASELINE_STALE_DAYS="${LM_BASELINE_STALE_DAYS:-30}"
  local BASELINE_PROGRESS_SET=0 BASELINE_PROGRESS=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --json) BASELINE_JSON=1; shift 1;;
      --stale-days) BASELINE_STALE_DAYS="$2"; shift 2;;
      --update) BASELINE_UPDATE=1; shift 1;;
      --local-only) BASELINE_LOCAL=1; shift 1;;
      --diff) BASELINE_DIFF=1; shift 1;;
      --show) BASELINE_SHOW=1; shift 1;;
      --progress) BASELINE_PROGRESS=1; BASELINE_PROGRESS_SET=1; shift 1;;
      --no-progress) BASELINE_PROGRESS=0; BASELINE_PROGRESS_SET=1; shift 1;;
      -h|--help)
        command_usage baseline
        exit 0;;
      *) echo "Unknown baseline flag: $1" >&2; exit 2;;
    esac
  done

  if [[ -z "$target" ]]; then
    command_usage baseline >&2
    exit 2
  fi

  if [[ "$target" == "status" ]]; then
    if [[ "$BASELINE_UPDATE" -eq 1 || "$BASELINE_LOCAL" -eq 1 || "$BASELINE_DIFF" -eq 1 || "$BASELINE_SHOW" -eq 1 || "$BASELINE_PROGRESS_SET" -eq 1 ]]; then
      echo "ERROR: baseline status only supports --json and --stale-days" >&2
      exit 2
    fi
    if [[ ! "$BASELINE_STALE_DAYS" =~ ^[0-9]+$ ]] || [[ "$BASELINE_STALE_DAYS" -lt 1 ]]; then
      echo "ERROR: --stale-days must be an integer >= 1" >&2
      exit 2
    fi
    BASELINE_STATUS_JSON="$BASELINE_JSON" \
    BASELINE_STATUS_STALE_DAYS="$BASELINE_STALE_DAYS" \
    BASELINE_STATUS_CFG_DIR="$(linux_maint_effective_cfg_dir)" \
    BASELINE_STATUS_SUMMARY_FILE="$(linux_maint_effective_summary_latest)" \
    python3 - <<'PY'
import json
import os
import pathlib
import time

cfg_dir = pathlib.Path(os.environ["BASELINE_STATUS_CFG_DIR"])
summary_path = pathlib.Path(os.environ["BASELINE_STATUS_SUMMARY_FILE"])
stale_days = int(os.environ["BASELINE_STATUS_STALE_DAYS"])
want_json = os.environ.get("BASELINE_STATUS_JSON", "0") == "1"
now = int(time.time())
stale_secs = stale_days * 86400

entries = [
    {"kind": "ports", "path": cfg_dir / "baselines" / "ports", "support_file": None, "monitor": "ports_baseline_monitor"},
    {"kind": "configs", "path": cfg_dir / "baselines" / "configs", "support_file": cfg_dir / "config_paths.txt", "monitor": "config_drift_monitor"},
    {"kind": "users", "path": cfg_dir / "baselines" / "users", "support_file": None, "monitor": "user_monitor"},
    {"kind": "sudoers", "path": cfg_dir / "baselines" / "sudoers", "support_file": None, "monitor": "user_monitor"},
]

severity_rank = {"CRIT": 4, "WARN": 3, "UNKNOWN": 2, "SKIP": 1, "OK": 0}
monitor_state = {}

if summary_path.is_file():
    try:
        for raw in summary_path.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw.strip()
            if not line.startswith("monitor="):
                continue
            fields = {}
            for token in line.split():
                if "=" not in token:
                    continue
                key, value = token.split("=", 1)
                fields[key] = value
            monitor = fields.get("monitor")
            if not monitor:
                continue
            status = fields.get("status", "UNKNOWN")
            reason = fields.get("reason")
            state = monitor_state.setdefault(monitor, {"status": "OK", "reason": None, "changed_hosts": 0})
            if severity_rank.get(status, -1) > severity_rank.get(state["status"], -1):
                state["status"] = status
                state["reason"] = reason
            elif state["reason"] is None and reason:
                state["reason"] = reason
            if reason in {"ports_baseline_changed", "config_drift_changed", "user_anomalies"}:
                state["changed_hosts"] += 1
    except OSError:
        pass

rows = []
for spec in entries:
    path = spec["path"]
    support = spec["support_file"]
    file_count = 0
    newest_mtime = None
    if path.is_dir():
        for child in sorted(path.iterdir()):
            if child.is_file():
                file_count += 1
                child_mtime = int(child.stat().st_mtime)
                newest_mtime = child_mtime if newest_mtime is None else max(newest_mtime, child_mtime)
    exists = path.exists()
    readable = os.access(path, os.R_OK) if exists else False
    age_seconds = None if newest_mtime is None else max(0, now - newest_mtime)
    latest = monitor_state.get(spec["monitor"], {"status": None, "reason": None, "changed_hosts": 0})
    rows.append(
        {
            "kind": spec["kind"],
            "path": str(path),
            "exists": exists,
            "readable": readable,
            "file_count": file_count,
            "latest_mtime_epoch": newest_mtime,
            "age_seconds": age_seconds,
            "stale": True if newest_mtime is None else age_seconds > stale_secs,
            "support_file": str(support) if support else None,
            "support_exists": support.exists() if support else None,
            "latest_status": latest["status"],
            "latest_reason": latest["reason"],
            "changed_hosts": latest["changed_hosts"],
        }
    )

if want_json:
    print(
        json.dumps(
            {
                "schema_version": 1,
                "baseline_status_json_contract_version": 1,
                "cfg_dir": str(cfg_dir),
                "summary_file": str(summary_path),
                "stale_days": stale_days,
                "items": rows,
            },
            indent=2,
            sort_keys=True,
        )
    )
else:
    print("linux-maint baseline status")
    print(f"cfg_dir={cfg_dir}")
    print(f"summary_file={summary_path}")
    print(f"stale_days={stale_days}")
    print("")
    print(f"{'kind':<9} {'files':>5} {'age':>8} {'stale':<6} {'latest':<8} details")
    for row in rows:
        if row["age_seconds"] is None:
            age_label = "-"
        elif row["age_seconds"] >= 86400:
            age_label = f"{row['age_seconds'] // 86400}d"
        elif row["age_seconds"] >= 3600:
            age_label = f"{row['age_seconds'] // 3600}h"
        elif row["age_seconds"] >= 60:
            age_label = f"{row['age_seconds'] // 60}m"
        else:
            age_label = f"{row['age_seconds']}s"
        details = [row["path"]]
        if row["support_file"]:
            details.append(f"input={'ok' if row['support_exists'] else 'missing'}")
        if row["latest_reason"]:
            details.append(f"reason={row['latest_reason']}")
        if row["changed_hosts"]:
            details.append(f"changed_hosts={row['changed_hosts']}")
        print(
            f"{row['kind']:<9} {row['file_count']:>5} {age_label:>8} {str(row['stale']).lower():<6} "
            f"{(row['latest_status'] or '-'): <8} {' '.join(details)}"
        )
PY
    exit 0
  fi

  if [[ "$BASELINE_DIFF" -eq 1 && "$BASELINE_SHOW" -eq 1 ]]; then
    echo "ERROR: use only one of --diff or --show" >&2
    exit 2
  fi
  if [[ "$BASELINE_JSON" -eq 1 ]]; then
    echo "ERROR: --json is only supported with baseline status" >&2
    exit 2
  fi
  if [[ "$BASELINE_STALE_DAYS" != "${LM_BASELINE_STALE_DAYS:-30}" ]]; then
    echo "ERROR: --stale-days is only supported with baseline status" >&2
    exit 2
  fi
  if [[ "$BASELINE_UPDATE" -eq 1 && ( "$BASELINE_DIFF" -eq 1 || "$BASELINE_SHOW" -eq 1 ) ]]; then
    echo "ERROR: --update cannot be combined with --diff or --show" >&2
    exit 2
  fi

  if [[ "$MODE" == "installed" && "$BASELINE_DIFF" -eq 0 && "$BASELINE_SHOW" -eq 0 ]]; then
    need_root_for baseline
  fi

  if [[ "$MODE" == "repo" ]]; then
    scripts_dir="$REPO_MONITORS"
  else
    scripts_dir="$LIBEXEC"
  fi

  case "$target" in
    ports)
      script="$scripts_dir/ports_baseline_monitor.sh"
      export LM_BASELINE_TARGET="ports"
      ;;
    configs|config)
      script="$scripts_dir/config_drift_monitor.sh"
      export LM_BASELINE_TARGET="configs"
      ;;
    users)
      script="$scripts_dir/user_monitor.sh"
      export LM_BASELINE_TARGET="users"
      ;;
    sudoers)
      script="$scripts_dir/user_monitor.sh"
      export LM_BASELINE_TARGET="sudoers"
      ;;
    *)
      echo "Unknown baseline target: $target" >&2
      exit 2
      ;;
  esac

  if [[ ! -x "$script" ]]; then
    echo "ERROR: baseline helper not found: $script" >&2
    exit 1
  fi

  export LM_BASELINE_ONLY=1
  if [[ "$BASELINE_UPDATE" -eq 1 ]]; then
    export BASELINE_UPDATE="true"
    export LM_HOST_PROGRESS=1
  fi
  if [[ "$BASELINE_LOCAL" -eq 1 ]]; then
    export LM_LOCAL_ONLY="true"
  fi
  if [[ "$BASELINE_DIFF" -eq 1 ]]; then
    export LM_BASELINE_DIFF=1
    export LM_BASELINE_ONLY=0
  fi
  if [[ "$BASELINE_SHOW" -eq 1 ]]; then
    export LM_BASELINE_SHOW=1
    export LM_BASELINE_ONLY=0
  fi

  if [[ "$BASELINE_PROGRESS_SET" -eq 1 ]]; then
    if [[ "$BASELINE_PROGRESS" -eq 1 ]]; then
      export LM_PROGRESS=1
      export LM_HOST_PROGRESS=1
    else
      export LM_PROGRESS=0
      export LM_HOST_PROGRESS=0
    fi
  fi

  exec bash "$script"
}

linux_maint_cmd_explain() {
  local sub="${1:-}" token f mon req opt purpose reasons st
  shift || true
  case "$sub" in
    reason)
      token="${1:-}"
      if [[ -z "$token" ]]; then
        echo "Usage: linux-maint explain reason <token>" >&2
        exit 2
      fi
      f="$(resolve_reasons_doc_path)"
      if [[ ! -f "$f" ]]; then
        echo "ERROR: reasons doc not found: $f" >&2
        exit 1
      fi
      if awk -v tok="$token" '
        BEGIN{sec=""; found=0}
        /^### /{sec=$0}
        $0 ~ "- `"tok"`" {
          if (sec!="") {print sec}
          print $0
          found=1
        }
        END{exit(found?0:1)}
      ' "$f"; then
        echo ""
        reason_next_steps "$token"
        exit 0
      fi

      if grep -n -i -F "$token" "$f" >/dev/null 2>&1; then
        echo "No exact token match; showing closest lines:" >&2
        grep -n -i -F "$token" "$f" | head -n 20
        exit 0
      fi
      echo "Unknown reason token: $token" >&2
      exit 1
      ;;

    monitor)
      mon="${1:-}"
      if [[ -z "$mon" ]]; then
        echo "Usage: linux-maint explain monitor <name>" >&2
        exit 2
      fi
      case "$mon" in
        health) mon="health_monitor" ;;
        inode) mon="inode_monitor" ;;
        disk_trend) mon="disk_trend_monitor" ;;
        network) mon="network_monitor" ;;
        service) mon="service_monitor" ;;
        ntp) mon="ntp_drift_monitor" ;;
        patch) mon="patch_monitor" ;;
        storage) mon="storage_health_monitor" ;;
        kernel_events) mon="kernel_events_monitor" ;;
        cert) mon="cert_monitor" ;;
        nfs) mon="nfs_mount_monitor" ;;
        ports) mon="ports_baseline_monitor" ;;
        config_drift) mon="config_drift_monitor" ;;
        user) mon="user_monitor" ;;
        backup) mon="backup_check" ;;
        inventory) mon="inventory_export" ;;
        preflight) mon="preflight_check" ;;
        config_validate|validate) mon="config_validate" ;;
      esac

      req=""
      opt=""
      while IFS='|' read -r m r o; do
        [[ -z "$m" ]] && continue
        if [[ "$m" == "$mon" ]]; then
          req="$r"
          opt="$o"
          break
        fi
      done <<'EOF_DEPS'
preflight_check|awk sed grep df timeout ssh|curl openssl
config_validate|awk sed grep|none
health_monitor|awk sed grep ps df|none
inode_monitor|awk sed grep df|none
disk_trend_monitor|awk sed grep df|none
network_monitor|awk sed grep|curl
service_monitor|awk sed grep|systemctl
ntp_drift_monitor|awk sed grep|chronyc ntpq
patch_monitor|awk sed grep|apt yum dnf zypper
storage_health_monitor|awk sed grep|smartctl nvme
kernel_events_monitor|awk sed grep|journalctl dmesg
cert_monitor|awk sed grep|openssl
nfs_mount_monitor|awk sed grep|showmount
ports_baseline_monitor|awk sed grep|ss netstat
config_drift_monitor|awk sed grep|sha256sum md5sum
user_monitor|awk sed grep|id getent
backup_check|awk sed grep|none
inventory_export|awk sed grep hostname|ip lsblk lscpu
EOF_DEPS

      if [[ -z "$req" && -z "$opt" ]]; then
        echo "Unknown monitor: $mon" >&2
        exit 2
      fi

      purpose="General health check"
      reasons="missing_dependency permission_denied"
      case "$mon" in
        preflight_check)
          purpose="Preflight readiness (deps/SSH/config)"
          reasons="missing_dependency missing_optional_cmd ssh_unreachable"
          ;;
        config_validate)
          purpose="Validate config file formats"
          reasons="config_invalid config_missing"
          ;;
        health_monitor)
          purpose="CPU/mem/load/disk snapshot"
          reasons="high_load high_mem disk_full"
          ;;
        inode_monitor)
          purpose="Inode utilization thresholds"
          reasons="inode_high"
          ;;
        disk_trend_monitor)
          purpose="Disk growth trend tracking"
          reasons="disk_growth disk_full"
          ;;
        network_monitor)
          purpose="Ping/TCP/HTTP reachability checks"
          reasons="ping_failed tcp_failed http_failed"
          ;;
        service_monitor)
          purpose="Systemd service health"
          reasons="service_inactive service_failed"
          ;;
        ntp_drift_monitor)
          purpose="Time sync health and drift"
          reasons="ntp_not_synced ntp_drift_high"
          ;;
        patch_monitor)
          purpose="Pending updates and reboot hints"
          reasons="security_updates_pending updates_pending reboot_required"
          ;;
        storage_health_monitor)
          purpose="RAID/SMART/NVMe health"
          reasons="raid_degraded smart_failed missing_dependency"
          ;;
        kernel_events_monitor)
          purpose="Kernel log scan (OOM/I/O/FS/hung tasks)"
          reasons="permission_denied missing_dependency"
          ;;
        cert_monitor)
          purpose="TLS certificate expiry/validity"
          reasons="cert_expiring cert_invalid"
          ;;
        nfs_mount_monitor)
          purpose="NFS mounted + responsive"
          reasons="timeout ssh_unreachable"
          ;;
        ports_baseline_monitor)
          purpose="Listening ports drift vs baseline"
          reasons="baseline_missing baseline_exists baseline_updated"
          ;;
        config_drift_monitor)
          purpose="Config drift vs baseline"
          reasons="config_missing baseline_missing"
          ;;
        user_monitor)
          purpose="User/sudoers drift + SSH failures"
          reasons="unexpected_user unexpected_sudoers_change failed_ssh_logins"
          ;;
        backup_check)
          purpose="Backup freshness/integrity"
          reasons="missing_dependency permission_denied"
          ;;
        inventory_export)
          purpose="HW/SW inventory export"
          reasons="missing_dependency permission_denied"
          ;;
      esac

      echo "monitor=$mon"
      echo "purpose=$purpose"
      echo "required_deps=${req:-none}"
      echo "optional_deps=${opt:-none}"
      echo "common_reasons=$reasons"
      echo "see=$(resolve_reasons_doc_path)"
      ;;

    status)
      st="${1:-}"
      if [[ -z "$st" ]]; then
        echo "Usage: linux-maint explain status <OK|WARN|CRIT|UNKNOWN|SKIP>" >&2
        exit 2
      fi
      case "$st" in
        OK) echo "OK: check succeeded; no action required." ;;
        WARN) echo "WARN: potential issue; attention suggested." ;;
        CRIT) echo "CRIT: actionable failure; immediate attention required." ;;
        UNKNOWN) echo "UNKNOWN: check could not be completed reliably (missing tool/permission/unexpected error)." ;;
        SKIP) echo "SKIP: check intentionally did not run (missing optional config/baseline/unsupported environment)." ;;
        *) echo "Unknown status: $st" >&2; exit 2 ;;
      esac
      ;;

    *)
      echo "Usage: linux-maint explain <reason|status|monitor> ..." >&2
      exit 2
      ;;
  esac
}

linux_maint_cmd_pack_logs() {
  local OUT="" pack_logs_bin _logdir _summarydir _state_dir _cfgdir _repo_root rc
  local PACK_PROGRESS_SET=0 PACK_PROGRESS=0 PACK_REDACT_SET=0 PACK_REDACT=0
  local PACK_HASH=0 PACK_GPG=0 PACK_GPG_KEEP=0 PACK_GPG_RECIPIENT=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out) OUT="${2:-}"; shift 2;;
      --progress) PACK_PROGRESS=1; PACK_PROGRESS_SET=1; shift 1;;
      --no-progress) PACK_PROGRESS=0; PACK_PROGRESS_SET=1; shift 1;;
      --redact) PACK_REDACT=1; PACK_REDACT_SET=1; shift 1;;
      --no-redact) PACK_REDACT=0; PACK_REDACT_SET=1; shift 1;;
      --hash) PACK_HASH=1; shift 1;;
      --gpg) PACK_GPG=1; shift 1;;
      --gpg-recipient) PACK_GPG=1; PACK_GPG_RECIPIENT="${2:-}"; shift 2;;
      --gpg-keep-plaintext) PACK_GPG_KEEP=1; shift 1;;
      -h|--help)
        command_usage pack-logs
        exit 0;;
      *) echo "Unknown pack-logs flag: $1" >&2; exit 2;;
    esac
  done

  if [[ -z "$OUT" ]]; then
    if [[ "$MODE" == "repo" ]]; then
      OUT="$REPO_ROOT"
    else
      OUT="."
    fi
  fi

  if [[ "$MODE" == "repo" ]]; then
    _logdir="$(linux_maint_effective_log_dir)"
    _summarydir="$(linux_maint_effective_summary_dir)"
    _state_dir="$(linux_maint_effective_notify_state_dir)"
    _cfgdir="$(linux_maint_effective_cfg_dir)"
    _repo_root="$REPO_ROOT"
  else
    _logdir="$(linux_maint_effective_log_dir)"
    _summarydir="$(linux_maint_effective_summary_dir)"
    _state_dir="$(linux_maint_effective_notify_state_dir)"
    _cfgdir="$(linux_maint_effective_cfg_dir)"
    _repo_root=""
  fi

  if [[ "$MODE" == "repo" ]]; then
    pack_logs_bin="$REPO_ROOT/tools/pack_logs.sh"
  else
    pack_logs_bin="$LIBEXEC/pack_logs.sh"
  fi
  if [[ ! -x "$pack_logs_bin" ]]; then
    echo "ERROR: pack-logs helper not found: $pack_logs_bin" >&2
    hint_line "reinstall or run from a git checkout." >&2
    exit 1
  fi
  if [[ "$PACK_PROGRESS_SET" -eq 1 ]]; then
    if [[ "$PACK_PROGRESS" -eq 1 ]]; then
      export LM_PROGRESS=1
    else
      export LM_PROGRESS=0
    fi
  fi

  if [[ "$PACK_REDACT_SET" -eq 1 ]]; then
    if [[ "$PACK_REDACT" -eq 1 ]]; then
      export LM_REDACT_LOGS=1
    else
      export LM_REDACT_LOGS=0
    fi
  fi

  if [[ "$PACK_HASH" -eq 1 ]]; then
    export LM_PACK_LOGS_HASH=1
  fi
  if [[ "$PACK_GPG" -eq 1 ]]; then
    export LM_PACK_LOGS_GPG=1
    export LM_PACK_LOGS_GPG_RECIPIENT="$PACK_GPG_RECIPIENT"
    export LM_PACK_LOGS_GPG_KEEP_PLAINTEXT="$PACK_GPG_KEEP"
  fi

  audit_log_append "pack-logs" "start" "out=$OUT log_dir=$_logdir summary_dir=$_summarydir state_dir=$_state_dir redact=${LM_REDACT_LOGS:-0}"
  set +e
  OUTDIR="$OUT" LOG_DIR="$_logdir" SUMMARY_DIR="$_summarydir" CFG_DIR="$_cfgdir" STATE_DIR="$_state_dir" REPO_ROOT="$_repo_root" \
    "$pack_logs_bin"
  rc=$?
  set -e
  audit_log_append "pack-logs" "$([[ "$rc" -eq 0 ]] && echo success || echo failure)" "rc=$rc out=$OUT"
  exit "$rc"
}
